name: Run Newman Tests

on:
  push:
    branches:
      - main

jobs:
  newman:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Dependencies
      run: npm install -g newman

    - name: Run Newman
      run: newman run NBA.postman_collection.json -e QA.postman_environment.json --reporters html --reporter-html-export report/report.html

    - name: Archive Newman HTML Report
      uses: actions/upload-artifact@v2
      with:
        name: newman-html-report
        path: report/report.html